### ISSUE TITLE
SMT

### ISSUE THREAD

**Issue by p4u** [liyue201/gnark-circomlib#1]
Hey, thanks for the job you are doing here! It's very useful.

Do you have plans to translate the circom SMT?

**Comment by liyue201** [comment]
> Hey, thanks for the job you are doing here! It's very useful.
> 
> Do you have plans to translate the circom SMT?

Yes, but I may not have time to do it recently

**Comment by p4u** [comment]
Hey, one of my team mate (@lucasmenendez) did it already, maybe you might want to include the code via PR to the repository. It is here https://github.com/vocdoni/gnark-prover-tinygo/tree/main/std/smt
